# Generated by Django 5.1.3 on 2025-01-19 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a particular chat session', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(help_text='Start time for a particular chat session')),
                ('open_session', models.BooleanField(default=True, help_text='Is this session currently open?')),
            ],
        ),
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('phone_num', models.CharField(help_text='Phone number of incoming messages', primary_key=True, serialize=False)),
                ('state', models.IntegerField(default=20, help_text='Status of a client as they move through session pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=2000)),
                ('response', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message received or sent')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='Unique ID for a particular chat session', null=True, on_delete=django.db.models.deletion.RESTRICT, to='whatsapp.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='client',
            field=models.ForeignKey(help_text='Phone number for incoming messages', null=True, on_delete=django.db.models.deletion.RESTRICT, to='whatsapp.clientlog'),
        ),
    ]
