# Generated by Django 5.1.3 on 2025-01-08 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a particular chat session', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(help_text='Start time for a particular chat session')),
            ],
        ),
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('phone_num', models.CharField(help_text='Phone number of incoming messages', primary_key=True, serialize=False)),
                ('state', models.IntegerField(help_text='Status of a client as they move through session pipeline')),
                ('waitlist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message received or sent')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.ForeignKey(help_text='Unique ID for a particular chat session', null=True, on_delete=django.db.models.deletion.RESTRICT, to='whatsapp.chatsession')),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='phone_num',
            field=models.ForeignKey(help_text='Phone number for incoming messages', null=True, on_delete=django.db.models.deletion.RESTRICT, to='whatsapp.clientlog'),
        ),
    ]
