# Generated by Django 5.1.3 on 2025-02-09 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 15, 16, 51, 368706)),
        ),
    ]
