# Generated by Django 5.1.3 on 2025-01-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_remove_clientlog_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlog',
            name='state',
            field=models.IntegerField(default=20, help_text='Status of a client as they move through session pipeline'),
        ),
    ]
