# Generated by Django 5.1.3 on 2025-01-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_alter_clientlog_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatlog',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='open_session',
            field=models.BooleanField(default=True, help_text='Is this session currently open?'),
        ),
    ]
