# Generated by Django 5.1.3 on 2025-01-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_rename_phone_num_chatsession_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='session_id',
            new_name='session',
        ),
    ]
