# Generated by Django 5.1.3 on 2025-02-10 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 16, 7, 10, 438167)),
        ),
    ]
