# Generated by Django 5.1.3 on 2025-02-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
